stages:
  train_model:
    cmd: python lstm_cnn_with_dvc.py --params params_v1.yaml --output metrics.npy --model model.h5
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v1.yaml
    outs:
    - metrics.npy
    - model.h5
    params:
      - learning_rate
  train_model_v2:
    cmd: python lstm_cnn_with_dvc.py --params params_v2.yaml --output metrics_v2.npy --model model_v2.h5
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml 
    outs:
    - metrics_v2.npy
    - model_v2.h5
    params:
    - learning_rate
