stages:
  train_model:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params.yaml  # Make sure params.yaml is listed here
    outs:
    - metrics.npy
    - model.h5
    params:
    - learning_rate  # Track learning_rate in params.yaml
    metrics:
    - metrics/metrics.json  # Track the metrics file (your saved metrics)
  train_model_v2:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml  # Make sure params.yaml is listed here
    outs:
    - metrics_v2.npy
    - model_v2.h5
    params:
    - learning_rate  # Track learning_rate in params.yaml
    metrics:
    - metrics/metrics.json  # Track the metrics file (your saved metrics)
