stages:
  train_model:
    cmd: python lstm_cnn_with_dvc.py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params.yaml
    outs:
    - outputs_train_model/metrics.npy
    - outputs_train_model/model.h5
    metrics:
    - metrics_train_model/metrics.json
    params:
      - learning_rate
  train_model_v2:
    cmd: python lstm_cnn_with_dvc.py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml 
    outs:
    - outputs_train_model_v2/metrics_v2.npy
    - outputs_train_model_v2/model_v2.h5
    metrics:
    - metrics_train_model_v2/metrics_v2.json
    params:
    - learning_rate
    - batch_size
