stages:
  train_model:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params.yaml
    outs:
    - metrics.npy
    - model.h5
    params:
    - params.yaml:learning_rate
    - params.yaml:batch_size
    metrics:
    - metrics/metrics.json 
  train_model_v2:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml 
    outs:
    - metrics_v2.npy
    - model_v2.h5
    params:
    - params_v2.yaml:learning_rate_v2
    - params_v2.yaml:batch_size_v2
    metrics:
    - metrics/metrics_v2.json 
