stages:
  train_model:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    outs:
    - metrics.npy
    - model.h5
