stages:
  train_model:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params.yaml
    outs:
    - outputs/train_model/metrics.npy
    - outputs/train_model/model.h5
    metrics:
    - metrics/train_model/metrics.json 
  train_model_v2:
    cmd: python lstm+cnn_(with-dvc).py
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml 
    outs:
    - outputs/train_model_v2/metrics_v2.npy
    - outputs/train_model_v2/model_v2.h5
    metrics:
    - metrics/train_model_v2/metrics_v2.json 
