stages:
  train_model:
    cmd: python lstm_cnn_with_dvc.py --params params.yaml --output metrics_v1.npy --model model_v1.h5
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params.yaml
    outs:
    - metrics_v1.npy
    - model_v1.h5
    params:
      - learning_rate
  train_model_v2:
    cmd: python lstm_cnn_with_dvc.py --params params_v2.yaml --output metrics_v2.npy --model model_v2.h5
    deps:
    - data.npz
    - test/data.npy
    - test/mask.npy
    - train/data.npy
    - train/mask.npy
    - params_v2.yaml 
    outs:
    - metrics_v2.npy
    - model_v2.h5
    params:
    - learning_rate
