name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Files Before Upload
        run: |
          ls -R :/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/ || echo "Directory not found!"


      # Step 4: Upload DVC Storage as Artifact from local machine
      - name: Upload DVC Storage as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dvc-storage
          path: C:/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/

      # Step 5: Run linting (optional)
      - name: Run Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 6: Install DVC
      - name: Install DVC
        run: pip install dvc

      # Step 7: Download DVC Storage Artifact (DVC cache)
      - name: Download DVC Storage Artifact
        uses: actions/download-artifact@v3
        with:
          name: dvc-storage
          path: C:/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/

      # Step 8: Pull DVC data
      - name: Pull DVC Data
        run: |
          dvc pull

      # Step 9: Debug Files (optional)
      - name: Debug Files
        run: |
          ls -R

      # Step 10: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest -s tests/test_script.py

      # Step 11: Execute script
      - name: Run Script
        run: |
          python lstm_cnn_with_dvc.py

      # Step 12: Push DVC changes (if applicable)
      - name: Push DVC Changes
        run: |
          dvc add data.npz
          dvc add params.yaml
          dvc add params_v2.yaml
          dvc repro
          dvc push
