name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run linting (optional)
      - name: Run Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest -s tests/test_script.py

      # Step 6: Execute script
      - name: Run Script
        run: |
          python lstm_cnn_with_dvc.py  # Ensure this is a valid Python command

  dvc-track-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install DVC
      - name: Install DVC
        run: pip install dvc

      # Step 3: Pull DVC data
      - name: Pull DVC Data
        run: |
          dvc pull

      # Step 4: Push DVC changes (if applicable)
      - name: Push DVC Changes
        run: |
          dvc add train/data.npy
          dvc add test/data.npy
          dvc push
