name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Cache DVC storage
      - name: Cache DVC storage
        uses: actions/cache@v3
        with:
          path: C:/Users/Tim/Desktop/ISRAT/RostockUniversity/PyCharmProjects/dvc_storage  # Path to your local DVC storage
          key: ${{ runner.os }}-dvc-storage-${{ hashFiles('**/dvc.yaml') }}  # Cache key based on dvc.yaml file changes
          restore-keys: |
            ${{ runner.os }}-dvc-storage-

      # Step 4: Run linting (optional)
      - name: Run Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 6: Install DVC
      - name: Install DVC
        run: pip install dvc

      # Step 7: Pull DVC data
      - name: Pull DVC Data
        run: |
          dvc pull

      # Step 8: Debug Files
      - name: Debug Files
        run: |
          ls -R

      # Step 9: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest -s tests/test_script.py

      # Step 10: Execute script
      - name: Run Script
        run: |
          python lstm_cnn_with_dvc.py

      # Step 11: Push DVC changes (if applicable)
      - name: Push DVC Changes
        run: |
          dvc add data.npz
          dvc add params.yaml
          dvc add params_v2.yaml
          dvc repro
          dvc push